### ISSUE TITLE
v2.0 Not working on my PC

### ISSUE THREAD

**Issue by cxagit** [SchnorcherSepp/TankWars2#1]
Tankwars v2.0 does not work on my PC. I just get some obscure error message talking about DirectX or something similar.
I am not satisfied with the experience so far.

**Comment by SchnorcherSepp** [comment]
can you post the error log

**Comment by cxagit** [comment]
![image](https://github.com/SchnorcherSepp/TankWars2/assets/9060772/10df6cb5-c78a-4601-a6ba-f215bf25e8fd)

**Comment by SchnorcherSepp** [comment]
aaa, i see ^^

**Comment by SchnorcherSepp** [comment]
fix with 2.1
